config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # -------- Public / Landing --------
  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end

  # -------- Authenticated Area --------
  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root

    resources :metals, only: [:index, :new, :create, :edit, :update]
    resources :purities, only: [:index, :new, :create, :edit, :update]
    resources :jewellery_categories, only: [:index, :new, :create, :edit, :update]
    resources :stock_ledgers
    resources :sales, only: [:index, :new, :create, :show]
    resources :companies
  end
end

app/views/layouts/_navbar.html.erb
<nav class="erp-navbar">
  <div class="navbar-container">
    
    <!-- Logo / Brand -->
    <div class="navbar-brand">
      💎 Rajesh Alankar Mandir
    </div>

    <!-- Navigation Links -->
    <ul class="navbar-links">
      <% if user_signed_in? %>
        <li><%= link_to "Dashboard", authenticated_root_path %></li>
        <ul class="navbar-links">
          <li><%= link_to "Metals", metals_path %></li>
          <li><%= link_to "Purities", purities_path %></li>
          <li><%= link_to "Categories", jewellery_categories_path %></li>
          <li><%= link_to "Inventory", stock_ledgers_path %></li>
          <li><%= link_to "Sales", sales_path %></li>
          <li><%= link_to "Reports", "#" %></li>
        </ul>
      <% end %>
    </ul>

    <!-- Auth Section -->
    <div class="navbar-auth">
      <% if user_signed_in? %>
        <span class="user-email">
          <%= current_user.email %>
        </span>

        <%= link_to "Logout",
                    destroy_user_session_path,
                    method: :delete,
                    class: "btn-logout" %>
      <% else %>
        <%= link_to "Login",
                    new_user_session_path,
                    class: "btn-login" %>
      <% end %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JewelryShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="page-container">
      <%= yield %>
    </div>
  </body>
</html>